version: '3'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

    working_dir: /usr/src/app
    command: npm run start
